### ISSUE TITLE
Page Route Error

### ISSUE THREAD

**Issue by zffMaple** [giscafer/wechat-weapp-mapdemo#1]
在定位页面，点击左上角的返回，报错。
![qq20160925-0](https://cloud.githubusercontent.com/assets/13342201/18814505/e708fa58-8347-11e6-8ce5-b6b843ba6bc0.png)

**Comment by giscafer** [comment]
这个是由于那个返回不是 小程序内置的返回。是微信内置地图页面的返回。所以报错了，目前我也没找到解决方法
导航的组件看API
https://mp.weixin.qq.com/debug/wxadoc/dev/component/navigator.html?t=1474644088081
