### ISSUE TITLE
为什么不使用地图组件?

### ISSUE THREAD

**Issue by ldarren** [giscafer/wechat-weapp-mapdemo#2]
为什么不使用[<map>地图组件](https://mp.weixin.qq.com/debug/wxadoc/dev/component/map.html#map)?

**Comment by giscafer** [comment]
嗯，可以获取经纬度，赋值地图组件。demo是早期小程序破解版，简单测试一下而已

**Comment by giscafer** [comment]
@ldarren 另外官方文档说了目前的开发工具版本不支持map组件

> 注意：开发工具暂时不支持map组件。
