### ISSUE TITLE
小程序真机演示

### ISSUE THREAD

**Issue by bestony** [giscafer/wechat-weapp-mapdemo#3]
Hi,我为您的小程序进行了真机测试。
具体您可以看这个[微信文章](http://mp.weixin.qq.com/s?__biz=MzA5NTQ4NjkyMQ==&mid=2650723004&idx=1&sn=a6bcbf354beca3e745c47e542e119e5c&chksm=88b4e41abfc36d0c547698b6f4f3669b1aa351a879332c2848ffd6618dbf23cb41316dca570a&scene=0#wechat_redirect)
视频源码已经上传至[WeApp-Demo](https://github.com/bestony/WeApp-Demo)

**Comment by giscafer** [comment]
@bestony 不错啊。有内测就是爽，看来我的demo定位缩放级别没写（已加上），还有没看到marker图标

**Comment by bestony** [comment]
如果内测期间，后续更新较多，我可以再次帮你测试一下。

**Comment by giscafer** [comment]
`  <map longitude="{{point.longitude}}" latitude="{{point.latitude}}" markers="{{markers}}" covers="{{covers}}"  scale="16" style="width: 320px; height:420px;"></map>
</scroll-view>
`
MAP组件加个`scale="16"`属性就可以了吧

**Comment by bestony** [comment]
这样应该是缩放级数有限制是吧？

**Comment by giscafer** [comment]
@bestony 是的
