### ISSUE TITLE
动态更新location

### ISSUE THREAD

**Issue by liupeng826** [giscafer/wechat-weapp-mapdemo#4]
你好，
我在开发者文档看到下面的信息，
https://mp.weixin.qq.com/debug/wxadoc/dev/component/map.html#map
地图组件的经纬度必填, 如果不填经纬度则默认值是北京的经纬度。 标记点markers只能在初始化的时候设置，不支持动态更新。

意思是不能更改marker位置吗？不能做到实时定位？

**Comment by giscafer** [comment]
应该支持的，你账户有测试资格吧？之前没公测是不行。公测后又权限应该可以的
