### ISSUE TITLE
如何给map上的markers或者covers上绑定事件

### ISSUE THREAD

**Issue by silbosu** [giscafer/wechat-weapp-mapdemo#5]
是否了解 如何给map上的markers或者covers上绑定事件？bindtap等……

**Comment by giscafer** [comment]
本demo开发的时候不支持，现在不清楚了。可以的话API应该有吧

**Comment by silbosu** [comment]
研究了一下他的事件文档，现在应该还不可以，唉~

**Comment by giscafer** [comment]
小程序不支持前端库我就没兴趣继续研究学习了，太封闭。生态目前也很烂。看今后能怎么样吧
